kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

steps:
  - name: Build
    image: node:latest
    environment:
      NPM_REGISTRY: http://192.168.1.2:4873/
    commands:
      - apt-get update
      - apt-get install build-essential sqlite3 libsqlite3-dev
      - npm install
      - make
      - npm run pack
