kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

steps:
  - name: Build
    image: node:latest
    environment:
      NPM_REGISTRY:
        from_secret: npm_registry_cache
      NPM_USER:
        from_secret: verdaccio_username
      NPM_PASS:
        from_secret: verdaccio_password
      NPM_EMAIL:
        from_secret: verdaccio_email
    commands:
      - npm install -g npm-login-noninteractive
      - npm-login-noninteractive
      - apt-get update
      - apt-get install -y build-essential sqlite3 libsqlite3-dev python
      - npm install
      - make
      - npm run pack
      - npm publish

  - name: Deploy wheel
    image: instrumentisto/rsync-ssh
    environment:
      PRIVATE_KEY:
        from_secret: ssh_private_key
    commands:
      - cd build/stage
      - echo "$PRIVATE_KEY" >> id_rsa
      - chmod 600 id_rsa
      - cd public
      - rsync -avz -e 'ssh -i ./id_rsa -o StrictHostKeyChecking=no' --progress ./* root@aricodes.net:/opt/sqlite3/
